/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

/** Type helpers */
type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never };
type XOR<T, U> = T | U extends object
  ? (Without<T, U> & U) | (Without<U, T> & T)
  : T | U;
type OneOf<T extends any[]> = T extends [infer Only]
  ? Only
  : T extends [infer A, infer B, ...infer Rest]
  ? OneOf<[XOR<A, B>, ...Rest]>
  : never;

export interface paths {
  "/pet": {
    /** Update an existing pet */
    put: operations["updatePet"];
    /** Add a new pet to the store */
    post: operations["addPet"];
  };
  "/pet/findByStatus": {
    /**
     * Finds Pets by status
     * @description Multiple status values can be provided with comma separated strings
     */
    get: operations["findPetsByStatus"];
  };
  "/pet/findByTags": {
    /**
     * Finds Pets by tags
     * @deprecated
     * @description Muliple tags can be provided with comma separated strings. Use         tag1, tag2, tag3 for testing.
     */
    get: operations["findPetsByTags"];
  };
  "/pet/{petId}": {
    /**
     * Find pet by ID
     * @description Returns a single pet
     */
    get: operations["getPetById"];
    /** Updates a pet in the store with form data */
    post: operations["updatePetWithForm"];
    /** Deletes a pet */
    delete: operations["deletePet"];
  };
  "/pet/{petId}/uploadImage": {
    /** uploads an image */
    post: operations["uploadFile"];
  };
  "/store/inventory": {
    /**
     * Returns pet inventories by status
     * @description Returns a map of status codes to quantities
     */
    get: operations["getInventory"];
  };
  "/store/order": {
    /** Place an order for a pet */
    post: operations["placeOrder"];
  };
  "/store/order/{orderId}": {
    /**
     * Find purchase order by ID
     * @description For valid response try integer IDs with value >= 1 and <= 10.         Other values will generated exceptions
     */
    get: operations["getOrderById"];
    /**
     * Delete purchase order by ID
     * @description For valid response try integer IDs with positive integer value.         Negative or non-integer values will generate API errors
     */
    delete: operations["deleteOrder"];
  };
  "/user": {
    /**
     * Create user
     * @description This can only be done by the logged in user.
     */
    post: operations["createUser"];
  };
  "/user/createWithArray": {
    /** Creates list of users with given input array */
    post: operations["createUsersWithArrayInput"];
  };
  "/user/createWithList": {
    /** Creates list of users with given input array */
    post: operations["createUsersWithListInput"];
  };
  "/user/login": {
    /** Logs user into the system */
    get: operations["loginUser"];
  };
  "/user/logout": {
    /** Logs out current logged in user session */
    get: operations["logoutUser"];
  };
  "/user/{username}": {
    /** Get user by user name */
    get: operations["getUserByName"];
    /**
     * Updated user
     * @description This can only be done by the logged in user.
     */
    put: operations["updateUser"];
    /**
     * Delete user
     * @description This can only be done by the logged in user.
     */
    delete: operations["deleteUser"];
  };
}

export interface components {
  schemas: {
    Order: {
      /** Format: int64 */
      id?: number;
      /** Format: int64 */
      petId?: number;
      /** Format: int32 */
      quantity?: number;
      /** Format: date-time */
      shipDate?: string;
      /**
       * @description Order Status
       * @enum {string}
       */
      status?: "placed" | "approved" | "delivered";
      /** @default false */
      complete?: boolean;
    };
    Category: {
      /** Format: int64 */
      id?: number;
      name?: string;
    };
    User: {
      /** Format: int64 */
      id?: number;
      username?: string;
      firstName?: string;
      lastName?: string;
      email?: string;
      password?: string;
      phone?: string;
      /**
       * Format: int32
       * @description User Status
       */
      userStatus?: number;
    };
    Tag: {
      /** Format: int64 */
      id?: number;
      name?: string;
    };
    Pet: {
      /** Format: int64 */
      id?: number;
      category?: components["schemas"]["Category"];
      /** @example doggie */
      name: string;
      photoUrls: string[];
      tags?: components["schemas"]["Tag"][];
      /**
       * @description pet status in the store
       * @enum {string}
       */
      status?: "available" | "pending" | "sold";
    };
    ApiResponse: {
      /** Format: int32 */
      code?: number;
      type?: string;
      message?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export interface operations {
  updatePet: {
    /** Update an existing pet */
    /** @description Pet object that needs to be added to the store */
    requestBody: {
      content: {
        "application/json": components["schemas"]["Pet"];
        "application/xml": components["schemas"]["Pet"];
      };
    };
    responses: {
      /** @description Invalid ID supplied */
      400: {
        content: {};
      };
      /** @description Pet not found */
      404: {
        content: {};
      };
      /** @description Validation exception */
      405: {
        content: {};
      };
    };
  };
  addPet: {
    /** Add a new pet to the store */
    /** @description Pet object that needs to be added to the store */
    requestBody: {
      content: {
        "application/json": components["schemas"]["Pet"];
        "application/xml": components["schemas"]["Pet"];
      };
    };
    responses: {
      /** @description Invalid input */
      405: {
        content: {};
      };
    };
  };
  findPetsByStatus: {
    /**
     * Finds Pets by status
     * @description Multiple status values can be provided with comma separated strings
     */
    parameters: {
      /** @description Status values that need to be considered for filter */
      query: {
        status: ("available" | "pending" | "sold")[];
      };
    };
    responses: {
      /** @description successful operation */
      200: {
        content: {
          "application/xml": components["schemas"]["Pet"][];
          "application/json": components["schemas"]["Pet"][];
        };
      };
      /** @description Invalid status value */
      400: {
        content: {};
      };
    };
  };
  findPetsByTags: {
    /**
     * Finds Pets by tags
     * @deprecated
     * @description Muliple tags can be provided with comma separated strings. Use         tag1, tag2, tag3 for testing.
     */
    parameters: {
      /** @description Tags to filter by */
      query: {
        tags: string[];
      };
    };
    responses: {
      /** @description successful operation */
      200: {
        content: {
          "application/xml": components["schemas"]["Pet"][];
          "application/json": components["schemas"]["Pet"][];
        };
      };
      /** @description Invalid tag value */
      400: {
        content: {};
      };
    };
  };
  getPetById: {
    /**
     * Find pet by ID
     * @description Returns a single pet
     */
    parameters: {
      /** @description ID of pet to return */
      path: {
        petId: number;
      };
    };
    responses: {
      /** @description successful operation */
      200: {
        content: {
          "application/xml": components["schemas"]["Pet"];
          "application/json": components["schemas"]["Pet"];
        };
      };
      /** @description Invalid ID supplied */
      400: {
        content: {};
      };
      /** @description Pet not found */
      404: {
        content: {};
      };
    };
  };
  updatePetWithForm: {
    /** Updates a pet in the store with form data */
    parameters: {
      /** @description ID of pet that needs to be updated */
      path: {
        petId: number;
      };
    };
    requestBody?: {
      content: {
        "application/x-www-form-urlencoded": {
          /** @description Updated name of the pet */
          name?: string;
          /** @description Updated status of the pet */
          status?: string;
        };
      };
    };
    responses: {
      /** @description Invalid input */
      405: {
        content: {};
      };
    };
  };
  deletePet: {
    /** Deletes a pet */
    parameters: {
      header?: {
        api_key?: string;
      };
      /** @description Pet id to delete */
      path: {
        petId: number;
      };
    };
    responses: {
      /** @description Invalid ID supplied */
      400: {
        content: {};
      };
      /** @description Pet not found */
      404: {
        content: {};
      };
    };
  };
  uploadFile: {
    /** uploads an image */
    parameters: {
      /** @description ID of pet to update */
      path: {
        petId: number;
      };
    };
    requestBody?: {
      content: {
        "multipart/form-data": {
          /** @description Additional data to pass to server */
          additionalMetadata?: string;
          /**
           * Format: binary
           * @description file to upload
           */
          file?: string;
        };
      };
    };
    responses: {
      /** @description successful operation */
      200: {
        content: {
          "application/json": components["schemas"]["ApiResponse"];
        };
      };
    };
  };
  getInventory: {
    /**
     * Returns pet inventories by status
     * @description Returns a map of status codes to quantities
     */
    responses: {
      /** @description successful operation */
      200: {
        content: {
          "application/json": {
            [key: string]: number | undefined;
          };
        };
      };
    };
  };
  placeOrder: {
    /** Place an order for a pet */
    /** @description order placed for purchasing the pet */
    requestBody: {
      content: {
        "*/*": components["schemas"]["Order"];
      };
    };
    responses: {
      /** @description successful operation */
      200: {
        content: {
          "application/xml": components["schemas"]["Order"];
          "application/json": components["schemas"]["Order"];
        };
      };
      /** @description Invalid Order */
      400: {
        content: {};
      };
    };
  };
  getOrderById: {
    /**
     * Find purchase order by ID
     * @description For valid response try integer IDs with value >= 1 and <= 10.         Other values will generated exceptions
     */
    parameters: {
      /** @description ID of pet that needs to be fetched */
      path: {
        orderId: number;
      };
    };
    responses: {
      /** @description successful operation */
      200: {
        content: {
          "application/xml": components["schemas"]["Order"];
          "application/json": components["schemas"]["Order"];
        };
      };
      /** @description Invalid ID supplied */
      400: {
        content: {};
      };
      /** @description Order not found */
      404: {
        content: {};
      };
    };
  };
  deleteOrder: {
    /**
     * Delete purchase order by ID
     * @description For valid response try integer IDs with positive integer value.         Negative or non-integer values will generate API errors
     */
    parameters: {
      /** @description ID of the order that needs to be deleted */
      path: {
        orderId: number;
      };
    };
    responses: {
      /** @description Invalid ID supplied */
      400: {
        content: {};
      };
      /** @description Order not found */
      404: {
        content: {};
      };
    };
  };
  createUser: {
    /**
     * Create user
     * @description This can only be done by the logged in user.
     */
    /** @description Created user object */
    requestBody: {
      content: {
        "*/*": components["schemas"]["User"];
      };
    };
    responses: {
      /** @description successful operation */
      default: {
        content: {};
      };
    };
  };
  createUsersWithArrayInput: {
    /** Creates list of users with given input array */
    /** @description List of user object */
    requestBody: {
      content: {
        "*/*": components["schemas"]["User"][];
      };
    };
    responses: {
      /** @description successful operation */
      default: {
        content: {};
      };
    };
  };
  createUsersWithListInput: {
    /** Creates list of users with given input array */
    /** @description List of user object */
    requestBody: {
      content: {
        "*/*": components["schemas"]["User"][];
      };
    };
    responses: {
      /** @description successful operation */
      default: {
        content: {};
      };
    };
  };
  loginUser: {
    /** Logs user into the system */
    parameters: {
      /** @description The user name for login */
      /** @description The password for login in clear text */
      query: {
        username: string;
        password: string;
      };
    };
    responses: {
      /** @description successful operation */
      200: {
        headers: {
          /** @description calls per hour allowed by the user */
          "X-Rate-Limit"?: number;
          /** @description date in UTC when token expires */
          "X-Expires-After"?: string;
        };
        content: {
          "application/xml": string;
          "application/json": string;
        };
      };
      /** @description Invalid username/password supplied */
      400: {
        content: {};
      };
    };
  };
  logoutUser: {
    /** Logs out current logged in user session */
    responses: {
      /** @description successful operation */
      default: {
        content: {};
      };
    };
  };
  getUserByName: {
    /** Get user by user name */
    parameters: {
      /** @description The name that needs to be fetched. Use user1 for testing. */
      path: {
        username: string;
      };
    };
    responses: {
      /** @description successful operation */
      200: {
        content: {
          "application/xml": components["schemas"]["User"];
          "application/json": components["schemas"]["User"];
        };
      };
      /** @description Invalid username supplied */
      400: {
        content: {};
      };
      /** @description User not found */
      404: {
        content: {};
      };
    };
  };
  updateUser: {
    /**
     * Updated user
     * @description This can only be done by the logged in user.
     */
    parameters: {
      /** @description name that need to be updated */
      path: {
        username: string;
      };
    };
    /** @description Updated user object */
    requestBody: {
      content: {
        "*/*": components["schemas"]["User"];
      };
    };
    responses: {
      /** @description Invalid user supplied */
      400: {
        content: {};
      };
      /** @description User not found */
      404: {
        content: {};
      };
    };
  };
  deleteUser: {
    /**
     * Delete user
     * @description This can only be done by the logged in user.
     */
    parameters: {
      /** @description The name that needs to be deleted */
      path: {
        username: string;
      };
    };
    responses: {
      /** @description Invalid username supplied */
      400: {
        content: {};
      };
      /** @description User not found */
      404: {
        content: {};
      };
    };
  };
}
